//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROGRA3_CAJR.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROGRA3_CAJR.Idioma.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string btn_Actualizar {
            get {
                return ResourceManager.GetString("btn_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btn_Eliminar {
            get {
                return ResourceManager.GetString("btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesar Empleado.
        /// </summary>
        internal static string btn_EliminarEmpleado {
            get {
                return ResourceManager.GetString("btn_EliminarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar Autos.
        /// </summary>
        internal static string btn_FiltrarAuto {
            get {
                return ResourceManager.GetString("btn_FiltrarAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar Clientes.
        /// </summary>
        internal static string btn_FiltrarCliente {
            get {
                return ResourceManager.GetString("btn_FiltrarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar Empleados.
        /// </summary>
        internal static string btn_FiltrarEmpleado {
            get {
                return ResourceManager.GetString("btn_FiltrarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string btn_FiltrarObjeto {
            get {
                return ResourceManager.GetString("btn_FiltrarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar trabajo.
        /// </summary>
        internal static string btn_FinalizarTrabajo {
            get {
                return ResourceManager.GetString("btn_FinalizarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar trabajo.
        /// </summary>
        internal static string btn_GenerarTrabajo {
            get {
                return ResourceManager.GetString("btn_GenerarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Auto.
        /// </summary>
        internal static string btn_IngresarAuto {
            get {
                return ResourceManager.GetString("btn_IngresarAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Cliente.
        /// </summary>
        internal static string btn_ingresarCliente {
            get {
                return ResourceManager.GetString("btn_ingresarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Empleado.
        /// </summary>
        internal static string btn_ingresarEmpleado {
            get {
                return ResourceManager.GetString("btn_ingresarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar objeto.
        /// </summary>
        internal static string btn_IngresarObjeto {
            get {
                return ResourceManager.GetString("btn_IngresarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string BTNCLIENTES {
            get {
                return ResourceManager.GetString("BTNCLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        internal static string BTNCONFUGURACION {
            get {
                return ResourceManager.GetString("BTNCONFUGURACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventarios.
        /// </summary>
        internal static string BTNEMPLEADOS {
            get {
                return ResourceManager.GetString("BTNEMPLEADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        internal static string BTNPRODUCTOS {
            get {
                return ResourceManager.GetString("BTNPRODUCTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Tema.
        /// </summary>
        internal static string BTNTEMA {
            get {
                return ResourceManager.GetString("BTNTEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajos.
        /// </summary>
        internal static string BTNVENTAS {
            get {
                return ResourceManager.GetString("BTNVENTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vista Previa.
        /// </summary>
        internal static string CONFPREV {
            get {
                return ResourceManager.GetString("CONFPREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string CONFSEL {
            get {
                return ResourceManager.GetString("CONFSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar registro..
        /// </summary>
        internal static string GB_ActualizarObjeto {
            get {
                return ResourceManager.GetString("GB_ActualizarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dar de baja a empleado..
        /// </summary>
        internal static string GB_EliminarEmpleado {
            get {
                return ResourceManager.GetString("GB_EliminarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar objeto..
        /// </summary>
        internal static string GB_EliminarObjeto {
            get {
                return ResourceManager.GetString("GB_EliminarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar autos por:.
        /// </summary>
        internal static string GB_FiltrarAutos {
            get {
                return ResourceManager.GetString("GB_FiltrarAutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar clientes por:.
        /// </summary>
        internal static string GB_FiltrarClientes {
            get {
                return ResourceManager.GetString("GB_FiltrarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar empleados por:.
        /// </summary>
        internal static string GB_FiltrarEmpleado {
            get {
                return ResourceManager.GetString("GB_FiltrarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar objetos por:.
        /// </summary>
        internal static string GB_FiltrarObjeto {
            get {
                return ResourceManager.GetString("GB_FiltrarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar un nuevo trabajo..
        /// </summary>
        internal static string GB_GenerarTrabajo {
            get {
                return ResourceManager.GetString("GB_GenerarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar un nuevo auto al cliente..
        /// </summary>
        internal static string GB_IngresoAutos {
            get {
                return ResourceManager.GetString("GB_IngresoAutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar un nuevo cliente..
        /// </summary>
        internal static string GB_IngresoClientes {
            get {
                return ResourceManager.GetString("GB_IngresoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar un nuevo empleado..
        /// </summary>
        internal static string GB_IngresoDeDatos {
            get {
                return ResourceManager.GetString("GB_IngresoDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar un nuevo objeto..
        /// </summary>
        internal static string GB_IngresoObjetos {
            get {
                return ResourceManager.GetString("GB_IngresoObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminar trabajo..
        /// </summary>
        internal static string GB_TerminarTrabajo {
            get {
                return ResourceManager.GetString("GB_TerminarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar cantidad.
        /// </summary>
        internal static string lbl_ActualizarCantidad {
            get {
                return ResourceManager.GetString("lbl_ActualizarCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar costo por unidad.
        /// </summary>
        internal static string lbl_ActualizarCostoUnidad {
            get {
                return ResourceManager.GetString("lbl_ActualizarCostoUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID del objeto a actualizar.
        /// </summary>
        internal static string lbl_ActualizarIdObjeto {
            get {
                return ResourceManager.GetString("lbl_ActualizarIdObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar nombre del objeto.
        /// </summary>
        internal static string lbl_ActualizarNombreObjeto {
            get {
                return ResourceManager.GetString("lbl_ActualizarNombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        internal static string lbl_ApMaterno {
            get {
                return ResourceManager.GetString("lbl_ApMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string lbl_ApPaterno {
            get {
                return ResourceManager.GetString("lbl_ApPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto del cliente.
        /// </summary>
        internal static string lbl_AutoDelCliente {
            get {
                return ResourceManager.GetString("lbl_AutoDelCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VencejoPIN.
        /// </summary>
        internal static string lbl_AutosVencejoPIN {
            get {
                return ResourceManager.GetString("lbl_AutosVencejoPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a.
        /// </summary>
        internal static string lbl_BienvenidoA {
            get {
                return ResourceManager.GetString("lbl_BienvenidoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string lbl_Cantidad {
            get {
                return ResourceManager.GetString("lbl_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lbl_Correo {
            get {
                return ResourceManager.GetString("lbl_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo del trabajo.
        /// </summary>
        internal static string lbl_CostoDelTrabajo {
            get {
                return ResourceManager.GetString("lbl_CostoDelTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo por unidad.
        /// </summary>
        internal static string lbl_CostoUnidad {
            get {
                return ResourceManager.GetString("lbl_CostoUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion del trabajo.
        /// </summary>
        internal static string lbl_DescripcionDelTrabajo {
            get {
                return ResourceManager.GetString("lbl_DescripcionDelTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad.
        /// </summary>
        internal static string lbl_Edad {
            get {
                return ResourceManager.GetString("lbl_Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empleado.
        /// </summary>
        internal static string lbl_EliminarIdEmpledo {
            get {
                return ResourceManager.GetString("lbl_EliminarIdEmpledo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID del objeto a eliminar.
        /// </summary>
        internal static string lbl_EliminarIdObjeto {
            get {
                return ResourceManager.GetString("lbl_EliminarIdObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del objeto a eliminar.
        /// </summary>
        internal static string lbl_EliminarNombreObjeto {
            get {
                return ResourceManager.GetString("lbl_EliminarNombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string lbl_EliminarPrimerAp {
            get {
                return ResourceManager.GetString("lbl_EliminarPrimerAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Nombre.
        /// </summary>
        internal static string lbl_EliminarPrimerNom {
            get {
                return ResourceManager.GetString("lbl_EliminarPrimerNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado encargado.
        /// </summary>
        internal static string lbl_EmpleadoEncargado {
            get {
                return ResourceManager.GetString("lbl_EmpleadoEncargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string lbl_FiltrarApPaterno {
            get {
                return ResourceManager.GetString("lbl_FiltrarApPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID del objeto a filtrar.
        /// </summary>
        internal static string lbl_FiltrarIdObjeto {
            get {
                return ResourceManager.GetString("lbl_FiltrarIdObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matricula.
        /// </summary>
        internal static string lbl_FiltrarMatricula {
            get {
                return ResourceManager.GetString("lbl_FiltrarMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo .
        /// </summary>
        internal static string lbl_FiltrarModelo {
            get {
                return ResourceManager.GetString("lbl_FiltrarModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del objeto a filtrar.
        /// </summary>
        internal static string lbl_FiltrarNombreObjeto {
            get {
                return ResourceManager.GetString("lbl_FiltrarNombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string lbl_FiltrarPrimerAp {
            get {
                return ResourceManager.GetString("lbl_FiltrarPrimerAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Nombre.
        /// </summary>
        internal static string lbl_FiltrarPrimerNom {
            get {
                return ResourceManager.GetString("lbl_FiltrarPrimerNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        internal static string lbl_FiltrarPuesto {
            get {
                return ResourceManager.GetString("lbl_FiltrarPuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Empleado.
        /// </summary>
        internal static string lbl_FiltrarssIdEmpleado {
            get {
                return ResourceManager.GetString("lbl_FiltrarssIdEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VencejoPIN.
        /// </summary>
        internal static string lbl_FiltrarVencejoPIN {
            get {
                return ResourceManager.GetString("lbl_FiltrarVencejoPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID del trabajo.
        /// </summary>
        internal static string lbl_Idtrabajo {
            get {
                return ResourceManager.GetString("lbl_Idtrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        internal static string lbl_Marca {
            get {
                return ResourceManager.GetString("lbl_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matricula.
        /// </summary>
        internal static string lbl_Matricula {
            get {
                return ResourceManager.GetString("lbl_Matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        internal static string lbl_Modelo {
            get {
                return ResourceManager.GetString("lbl_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del objeto.
        /// </summary>
        internal static string lbl_NombreObjeto {
            get {
                return ResourceManager.GetString("lbl_NombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero Telefonico.
        /// </summary>
        internal static string lbl_NumeroTelefonico {
            get {
                return ResourceManager.GetString("lbl_NumeroTelefonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string lbl_PrimerAp {
            get {
                return ResourceManager.GetString("lbl_PrimerAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Nombre.
        /// </summary>
        internal static string lbl_PrimerNom {
            get {
                return ResourceManager.GetString("lbl_PrimerNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        internal static string lbl_Puesto {
            get {
                return ResourceManager.GetString("lbl_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        internal static string lbl_SegundoAp {
            get {
                return ResourceManager.GetString("lbl_SegundoAp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Nombre.
        /// </summary>
        internal static string lbl_SegundoNom {
            get {
                return ResourceManager.GetString("lbl_SegundoNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero Telefonico.
        /// </summary>
        internal static string lbl_Telefono {
            get {
                return ResourceManager.GetString("lbl_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string lbl_TituloClientes {
            get {
                return ResourceManager.GetString("lbl_TituloClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        internal static string lbl_TituloEmpleados {
            get {
                return ResourceManager.GetString("lbl_TituloEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventarios.
        /// </summary>
        internal static string lbl_TituloInventarios {
            get {
                return ResourceManager.GetString("lbl_TituloInventarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Trabajos.
        /// </summary>
        internal static string lbl_TituloTrabajos {
            get {
                return ResourceManager.GetString("lbl_TituloTrabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lbl_usuario {
            get {
                return ResourceManager.GetString("lbl_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VencejoPIN.
        /// </summary>
        internal static string lbl_VencejoPIN {
            get {
                return ResourceManager.GetString("lbl_VencejoPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea salir?.
        /// </summary>
        internal static string MENSAJESALIR {
            get {
                return ResourceManager.GetString("MENSAJESALIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string TOOLAYUDA {
            get {
                return ResourceManager.GetString("TOOLAYUDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion.
        /// </summary>
        internal static string TOOLCERRAR {
            get {
                return ResourceManager.GetString("TOOLCERRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        internal static string TOOLINFO {
            get {
                return ResourceManager.GetString("TOOLINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string TOOLINICIO {
            get {
                return ResourceManager.GetString("TOOLINICIO", resourceCulture);
            }
        }
    }
}
